BayMaxShop/BayMaxShop/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace BayMaxShop.Models
{
    public class ContactViewModel
    {
        public string ReplyMessage { get; set; }
    }
}

BayMaxShop/BayMaxShop/Models/EF/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BayMaxShop.Models.EF
{
    [Table("Contact")]
    public class Contact
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [EmailAddress]
        [Required]
        public string Email { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Message { get; set; }
        public string ReplyMessage { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

BayMaxShop/BayMaxShop/Areas/Admin/Controllers/ContactController.cs
using BayMaxShop.Models;
using BayMaxShop.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BayMaxShop.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin, Staff")]
    public class ContactController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult DsContact()
        {
            try
            {
                var contact = db.Contacts.OrderByDescending(x => x.CreatedDate).Select(x => new
                {
                    id = x.Id,
                    name = x.Name,
                    email = x.Email,
                    message = x.Message
                })
                .ToList();
                return Json(new { code = 200, dsContact = contact, msg = "Successfully get list contact!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Get list contact false: " + ex.Message, JsonRequestBehavior.AllowGet });
            }
        }

        [HttpGet]
        public JsonResult Reply(int id)
        {
            try
            {
                var detail = db.Contacts.Where(i => i.Id == id).Select(i => new
                {
                    id = i.Id,
                    name = i.Name,
                    email = i.Email
                })
                .SingleOrDefault();
                return Json(new { code = 200, detail = detail, msg = "Successfully get detail!" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { code = 500, msg = "Failed get detail!" + ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult SendMail(string name, string email, string subject)
        {
            var result = BayMaxShop.Common.Common.SendMail(name, subject, "<p>Xin chào " + name + ",<br /> " + subject + " <br />Cảm ơn bạn liên hệ với chúng tôi.</p>", email);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

BayMaxShop/BayMaxShop/Areas/Admin/Controllers/HomeController.cs
using BayMaxShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BayMaxShop.Areas.Admin.Controllers
{
    //[Authorize(Roles = "Admin, Staff")]
    public class HomeController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/Home
        public ActionResult Index()
        {
            if (User.IsInRole("Customer"))
            {
                // Người dùng là Customer, chuyển hướng đến trang customer
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            ViewBag.Orders = db.Orders.Count();
            ViewBag.Products = db.Products.Count();
            ViewBag.News = db.News.Count();
            ViewBag.Account = db.Users.Count();
            return View();
        }
    }
}

BayMaxShop/BayMaxShop/Controllers/ContactController.cs
using BayMaxShop.Models;
using BayMaxShop.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BayMaxShop.Controllers
{
    public class ContactController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Contact model)
        {
            if (ModelState.IsValid) 
            {
                model.CreatedDate = DateTime.Now;
                db.Contacts.Add(model);
                db.SaveChanges();
            }
            return View(model);
        }
    }
}

BayMaxShop/BayMaxShop/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BayMaxShop.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (User.IsInRole("Admin"))
            {
                // Người dùng là admin, chuyển hướng đến trang admin
                return RedirectToAction("Index", "Home", new { area = "Admin" });
            }
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Partial_Subcrice()
        {
            return PartialView();
        }
    }
}

BayMaxShop/BayMaxShop/Controllers/MenuController.cs
using BayMaxShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BayMaxShop.Controllers
{
    public class MenuController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MenuTop() 
        {
            var items = db.Menus.OrderByDescending(x => x.Position).ToList();
            return PartialView("MenuTop",items);
        }
        public ActionResult MenuProductCategory()
        {
            var items = db.ProductCategories.ToList();
            return PartialView("MenuProductCategory", items);
        }
        public ActionResult MenuArrival() 
        { 
            var items = db.ProductCategories.ToList();
            return PartialView("MenuArrival",items); 
        }
        public ActionResult MenuLeft(int? id)
        {
            if (id != null)
            {
                ViewBag.CateId = id;
            }
            var items = db.ProductCategories.ToList();
            return PartialView("MenuLeft", items);
        }
        public ActionResult MenuBrand(int? id) 
        {
            if (id != null) 
            {
                ViewBag.BrId = id;
            }
            var items = db.Brands.ToList();
            return PartialView("MenuBrand", items);
        }
    }
}

BayMaxShop/BayMaxShop/Controllers/NewsController.cs
using BayMaxShop.Models.EF;
using BayMaxShop.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BayMaxShop.Controllers
{
    public class NewsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: News
        public ActionResult Index(int? page)
        {
            var pageSize = 1;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<News> items = db.News.OrderByDescending(x => x.CreatedDate);
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Detail(int id)
        {
            var item = db.News.Find(id);
            return View(item);
        }
        public ActionResult Partial_News_Home()
        {
            var items = db.News.Take(3).ToList();
            return PartialView(items);
        }
    }
}

BayMaxShop/BayMaxShop/Controllers/ProductsController.cs
using BayMaxShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using PagedList;
using BayMaxShop.Models.EF;

namespace BayMaxShop.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Products
        public ActionResult Index(string Searchtext, int? page)
        {
            

            var pageSize = 12;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Product> items = db.Products.OrderByDescending(x => x.Id);
            if (!string.IsNullOrEmpty(Searchtext))
            {

                items = items.Where(x => x.Alias.Contains(Searchtext) || x.ProductName.Contains(Searchtext));
            }
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }

        public ActionResult Detail(string alias, int id)
        {
            var item = db.Products.Find(id);
            return View(item);
        }

        public ActionResult ProductCategory(string alias, int? id, string Searchtext, int? page)
        {
          
            var pageSize = 12;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Product> items = db.Products.OrderByDescending(x => x.Id);
            if (!string.IsNullOrEmpty(Searchtext))
            {

                items = items.Where(x => x.Alias.Contains(Searchtext) || x.ProductName.Contains(Searchtext));
            }
            if (id > 0)
            {
                items = items.Where(x => x.ProductCategoryId == id).ToList();
            }
            var cate = db.ProductCategories.Find(id);
            if (cate != null)
            {
                ViewBag.CateName = cate.ProductCategoryName;
            }

            ViewBag.CateId = id;
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }

        public ActionResult ProductBrand(string alias, int? id, string Searchtext, int? page)
        {

            var pageSize = 12;
            if (page == null)
            {
                page = 1;
            }
            IEnumerable<Product> items = db.Products.OrderByDescending(x => x.Id);
            if (!string.IsNullOrEmpty(Searchtext))
            {

                items = items.Where(x => x.Alias.Contains(Searchtext) || x.ProductName.Contains(Searchtext));
            }
            if (id > 0)
            {
                items = items.Where(x => x.BrandId == id).ToList();
            }
            var cate = db.Brands.Find(id);
            if (cate != null)
            {
                ViewBag.CateName = cate.BrandName;
            }

            ViewBag.BrandId = id;
            var pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            items = items.ToPagedList(pageIndex, pageSize);
            ViewBag.PageSize = pageSize;
            ViewBag.Page = page;
            return View(items);
        }
        public ActionResult Partial_ItemsByCateId() 
        {
            var items = db.Products.Where(x => x.IsHome && x.IsActive == true).Take(12).ToList();
            return PartialView(items);
        }
        public ActionResult Partial_ProductSales()
        {
            var items = db.Products.Where(x => x.IsSale && x.IsActive == true).Take(12).ToList();
            return PartialView(items);
        }
    }
}

BayMaxShop/BayMaxShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BayMaxShop/BayMaxShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BayMaxShop/BayMaxShop/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<link rel="stylesheet" type="text/css" href="~/Content/assets/styles/main_styles.css">
<link rel="stylesheet" href="~/Content/assets/styles/Slider.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<!-- Deal of the week -->
@*<div class="main_slider" style="background-image: url(/Content/assets/images/banner_chinh.jpg); top: -75px; height: 850px;">
        <div class="container fill_height">
            <div class="row align-items-center fill_height">
                <div class="col">
                </div>
            </div>
        </div>
    </div>*@
<div class="slider">
    <div class="slides">
        <input type="radio" name="radio-btn" id="radio1" />
        <input type="radio" name="radio-btn" id="radio2" />
        <input type="radio" name="radio-btn" id="radio3" />
        <div class="slide first">
            <img src="~/Content/assets/images/banner2.png" alt="" />
        </div>
        <div class="slide">
            <img src="~/Content/assets/images/BigSale.png" alt="" />
        </div>
        <div class="slide">
            <img src="~/Content/assets/images/banner_chinh.jpg" alt="" />
        </div>
        <div class="navigation-auto">
            <div class="auto-btn1"></div>
            <div class="auto-btn2"></div>
            <div class="auto-btn3"></div>
        </div>
        @*        <div class="navigation-manual">
                <label for="radio1" class="manual-btn"></label>
                <label for="radio2" class="manual-btn"></label>
                <label for="radio3" class="manual-btn"></label>
            </div>*@
    </div>
</div>


<!-- Banner -->

@Html.Action("MenuProductCategory", "Menu")

<!-- New Arrivals -->
@*<div class="new_arrivals">
        <div class="container">
            @Html.Action("MenuArrival", "Menu")
        </div>
    </div>*@


<!-- Best Sellers -->

<div class="best_sellers">
    @Html.Action("Partial_ProductSales", "Products")
</div>

<!-- Benefit -->

<div style="font-family:'Times New Roman', Times, serif;" class="benefit">
    <div class="container">
        <div class="row benefit_row">
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i style="color:orange" class="fas fa-truck-pickup" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Giảm Giá 50%</h6>

                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i style="color: orange " class="fa fa-cash-register" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Bảo Hành 1 Năm</h6>

                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i style="color: orange " class="fa fa-safari" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Hàng Thật 100%</h6>

                    </div>
                </div>
            </div>
            <div class="col-lg-3 benefit_col">
                <div class="benefit_item d-flex flex-row align-items-center">
                    <div class="benefit_icon"><i style="color:orange " class="fa fa-door-open" aria-hidden="true"></i></div>
                    <div class="benefit_content">
                        <h6>Hoạt Động 24/7</h6>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var counter = 1;
    setInterval(function () {
        document.getElementById('radio' + counter).checked = true;
        counter++;
        if (counter > 3) {
            counter = 1;
        }
    }, 3000);
</script>
<!-- Blogs -->

@Html.Action("Partial_News_Home", "News")